[server]
vardir = /opt/puppetlabs/server/data/puppetserver
logdir = /var/log/puppetlabs/puppetserver
rundir = /var/run/puppetlabs/puppetserver
pidfile = /var/run/puppetlabs/puppetserver/puppetserver.pid
codedir = /etc/puppetlabs/code
dns_alt_names = jumpstart,jumpstart.internal.local,puppet,puppet.internal.local

[main]
certname = jumpstart.internal.local
server = jumpstart.internal.local
environment = production
runinterval = 30m
ssldir = /etc/puppetlabs/puppet/ssl
